#!/usr/bin/env bash
#
# Installs the "wsg" command for the current user.
#
# Exports WSG_HOME (the folder of this script) from the shell start-up file,
# writes a small launcher into ~/.local/bin and makes sure that folder is on
# PATH. Nothing outside the home folder is touched.
#
# Usage: bash install.sh [bin-folder]
#
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ENTRY_POINT="$SCRIPT_DIR/wsg.py"
BIN_DIR="${1:-$HOME/.local/bin}"
LAUNCHER="$BIN_DIR/wsg"

MARK_START="# >>> wsg >>>"
MARK_END="# <<< wsg <<<"

if [ ! -f "$ENTRY_POINT" ]; then
    echo "wsg.py was not found next to this script ($SCRIPT_DIR)." >&2
    exit 1
fi

if command -v python3 >/dev/null 2>&1; then
    PYTHON=python3
elif command -v python >/dev/null 2>&1; then
    PYTHON=python
else
    echo "Python 3 was not found in PATH. Install it and run this script again." >&2
    exit 1
fi

echo "[wsg] python interpreter: $PYTHON"
echo "[wsg] installation dir  : $SCRIPT_DIR"

# --- launcher ----------------------------------------------------------------
mkdir -p "$BIN_DIR"
cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Generated by install.sh -- do not edit, run the installer again instead.
WSG_HOME="\${WSG_HOME:-$SCRIPT_DIR}"
exec $PYTHON "\$WSG_HOME/wsg.py" "\$@"
EOF
chmod +x "$LAUNCHER"
echo "[wsg] launcher created  : $LAUNCHER"

# --- shell start-up files ----------------------------------------------------
write_block() {
    local rc="$1"
    [ -e "$rc" ] || return 0
    # Remove an older block first so that the script stays idempotent.
    if grep -qF "$MARK_START" "$rc"; then
        sed -i.wsgbak "\|$MARK_START|,\|$MARK_END|d" "$rc"
        rm -f "$rc.wsgbak"
    fi
    cat >> "$rc" <<EOF
$MARK_START
export WSG_HOME="$SCRIPT_DIR"
case ":\$PATH:" in
    *":$BIN_DIR:"*) ;;
    *) export PATH="$BIN_DIR:\$PATH" ;;
esac
$MARK_END
EOF
    echo "[wsg] updated           : $rc"
    UPDATED=1
}

UPDATED=0
write_block "$HOME/.bashrc"
write_block "$HOME/.zshrc"
if [ "$UPDATED" -eq 0 ]; then
    touch "$HOME/.profile"
    write_block "$HOME/.profile"
fi

# --- check -------------------------------------------------------------------
WSG_HOME="$SCRIPT_DIR" "$LAUNCHER" --version

echo
echo "[wsg] done. Open a new terminal (or run: source ~/.bashrc) and try: wsg --help"
