<#
.SYNOPSIS
    Installs the "wsg" command for the current user (no administrator rights).

.DESCRIPTION
    Stores the location of this folder in the user environment variable
    WSG_HOME, creates a small wsg.cmd launcher and puts its folder on the
    user PATH. Nothing is written outside the user profile.

    The user PATH is written through the registry so that its type
    (REG_EXPAND_SZ) and any %VARIABLE% references it contains are preserved.
    After the change a WM_SETTINGCHANGE message is broadcast, which makes
    Explorer -- and every program started from it afterwards -- pick up the
    new environment.

.PARAMETER BinDir
    Folder the launcher is written into. Default:
    %LOCALAPPDATA%\Programs\wsg\bin

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File .\install.ps1
#>
[CmdletBinding()]
param(
    [string]$BinDir = (Join-Path $env:LOCALAPPDATA 'Programs\wsg\bin')
)

$ErrorActionPreference = 'Stop'
$environmentKey = 'HKCU:\Environment'

# --- helpers -----------------------------------------------------------------
function Get-UserPath {
    <# Returns the raw user PATH together with its registry type. #>
    $item = Get-Item -LiteralPath $environmentKey
    $kind = 'ExpandString'
    $raw = ''
    if ($item.GetValueNames() -contains 'Path') {
        $kind = [string]$item.GetValueKind('Path')
        $raw = [string]$item.GetValue('Path', '', 'DoNotExpandEnvironmentNames')
    }
    return [PSCustomObject]@{ Raw = $raw; Kind = $kind }
}

function Set-UserPath {
    param([string]$Value, [string]$Kind)
    Set-ItemProperty -LiteralPath $environmentKey -Name 'Path' -Value $Value -Type $Kind
}

function Publish-EnvironmentChange {
    <# Tells the running shell of Windows that the environment has changed. #>
    try {
        if (-not ('Wsg.NativeMethods' -as [type])) {
            Add-Type -Namespace 'Wsg' -Name 'NativeMethods' -MemberDefinition @'
[System.Runtime.InteropServices.DllImport("user32.dll", SetLastError = true, CharSet = System.Runtime.InteropServices.CharSet.Auto)]
public static extern System.IntPtr SendMessageTimeout(System.IntPtr hWnd, uint msg, System.UIntPtr wParam, string lParam, uint flags, uint timeout, out System.UIntPtr result);
'@
        }
        $unused = [System.UIntPtr]::Zero
        $null = [Wsg.NativeMethods]::SendMessageTimeout(
            [System.IntPtr]0xffff, 0x1A, [System.UIntPtr]::Zero, 'Environment', 0x0002, 3000, [ref]$unused)
        return $true
    }
    catch {
        return $false
    }
}

# --- program folder ----------------------------------------------------------
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$entryPoint = Join-Path $scriptDir 'wsg.py'
if (-not (Test-Path -LiteralPath $entryPoint)) {
    throw "wsg.py was not found next to this script ($scriptDir)."
}

# --- Python interpreter ------------------------------------------------------
if (Get-Command py -ErrorAction SilentlyContinue) {
    $launcher = 'py -3'
}
elseif (Get-Command python -ErrorAction SilentlyContinue) {
    $launcher = 'python'
}
else {
    throw 'Python 3 was not found in PATH. Install it from https://www.python.org and run this script again.'
}
Write-Host "[wsg] python launcher : $launcher"
Write-Host "[wsg] installation dir: $scriptDir"

# --- launcher ----------------------------------------------------------------
New-Item -ItemType Directory -Force -Path $BinDir | Out-Null
$cmdPath = Join-Path $BinDir 'wsg.cmd'
$cmdBody = @"
@echo off
rem Generated by install.ps1 -- do not edit, run the installer again instead.
if not defined WSG_HOME (
    echo wsg: WSG_HOME is not set. Close this terminal completely, open a new
    echo      one and try again. If that does not help, run install.ps1 again.
    exit /b 1
)
$launcher "%WSG_HOME%\wsg.py" %*
"@
Set-Content -LiteralPath $cmdPath -Value $cmdBody -Encoding ASCII
Write-Host "[wsg] launcher created: $cmdPath"

# --- environment variable ----------------------------------------------------
[Environment]::SetEnvironmentVariable('WSG_HOME', $scriptDir, 'User')
$env:WSG_HOME = $scriptDir
Write-Host "[wsg] WSG_HOME set for the current user"

# --- user PATH ---------------------------------------------------------------
$path = Get-UserPath
$parts = @($path.Raw.Split(';') | Where-Object { $_ -ne '' })
$kind = $path.Kind

# Path is a REG_EXPAND_SZ value by convention; repair the type when some tool
# (including an older version of this script) has turned it into a plain string.
if ($kind -eq 'String' -and $path.Raw -notmatch '%') {
    $kind = 'ExpandString'
    Write-Host '[wsg] user PATH type restored to REG_EXPAND_SZ'
}

if ($parts -notcontains $BinDir) {
    Set-UserPath -Value (($parts + $BinDir) -join ';') -Kind $kind
    Write-Host "[wsg] added to the user PATH: $BinDir"
}
elseif ($kind -ne $path.Kind) {
    Set-UserPath -Value ($parts -join ';') -Kind $kind
    Write-Host "[wsg] already on the user PATH: $BinDir"
}
else {
    Write-Host "[wsg] already on the user PATH: $BinDir"
}

if (($env:Path -split ';') -notcontains $BinDir) {
    $env:Path = "$env:Path;$BinDir"
}

if (Publish-EnvironmentChange) {
    Write-Host '[wsg] environment change broadcast to the system'
}
else {
    Write-Warning 'the environment change could not be broadcast; a sign out may be needed'
}

# --- check -------------------------------------------------------------------
& $cmdPath --version

Write-Host ''
Write-Host '[wsg] done.'
Write-Host ''
Write-Host 'Terminals that were already running keep the environment they were'
Write-Host 'started with -- a new tab or a new window of the same application is'
Write-Host 'not enough. Close Windows Terminal / VS Code / the console host'
Write-Host 'completely and start it again, then run: wsg --help'
Write-Host ''
Write-Host 'To use wsg in this very window right away, paste this single line:'
Write-Host ''
Write-Host "  `$env:WSG_HOME = '$scriptDir'; `$env:Path += ';$BinDir'"
Write-Host ''
